spring.application.name=studyflow
# Endereço e porta do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/studyflow
spring.datasource.username=root
spring.datasource.password=HINGBORN@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
